modLoader = "lowcodefml"
loaderVersion = "[25,)"
license = "GPL-3.0"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Prometheus"
description = "${description}"
logoFile = "assets/prometheus/icon.png"
authors = ["dxxxxy"]
displayURL = "https://discord.gg/zXFKGhRKZQ"