modLoader = "lowcodefml"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/prometheusreengineering/prometheus-minecraft"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Prometheus"
description = "${description}"
logoFile = "assets/prometheus/icon.png"
logoBlur = false
authors = ["dxxxxy", "Cootshk"]
displayURL = "https://discord.gg/zXFKGhRKZQ"